/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f5",
        "secondary": "#755b00",
        "surface-dim": "#e1d8d4",
        "primary-fixed-dim": "#ffb2b7",
        "on-background": "#1e1b18",
        "on-surface": "#1e1b18",
        "outline": "#877273",
        "inverse-primary": "#ffb2b7",
        "outline-variant": "#dac0c1",
        "on-primary-fixed-variant": "#7b2b36",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffe08f",
        "tertiary-fixed-dim": "#c8c6c3",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f8efea",
        "primary-fixed": "#ffdadb",
        "secondary-container": "#fed977",
        "on-tertiary-fixed-variant": "#474744",
        "surface-container-high": "#efe6e2",
        "primary": "#4e0816",
        "on-primary-container": "#ee868f",
        "surface-container-highest": "#e9e1dc",
        "on-secondary-fixed-variant": "#584400",
        "on-tertiary-container": "#a6a5a1",
        "tertiary-fixed": "#e4e2de",
        "on-error-container": "#93000a",
        "inverse-surface": "#34302c",
        "tertiary": "#252523",
        "surface-bright": "#fff8f5",
        "secondary-fixed-dim": "#e6c364",
        "on-secondary-fixed": "#241a00",
        "on-primary-fixed": "#40000e",
        "error-container": "#ffdad6",
        "surface-tint": "#99424c",
        "surface-container-low": "#fbf2ed",
        "on-tertiary-fixed": "#1b1c1a",
        "primary-container": "#6b1f2a",
        "tertiary-container": "#3a3b38",
        "on-error": "#ffffff",
        "surface-variant": "#e9e1dc",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#544243",
        "on-secondary-container": "#785d00",
        "surface-container": "#f5ece7",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "background": "#fff8f5",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "base": "8px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "gutter-desktop": "24px",
        "gutter-mobile": "16px",
      },
      fontFamily: {
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": [
          "36px",
          {
            lineHeight: "1.2",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "1.6",
            fontWeight: "400",
          },
        ],
        "headline-md": [
          "32px",
          {
            lineHeight: "1.3",
            fontWeight: "600",
          },
        ],
        "headline-sm": [
          "24px",
          {
            lineHeight: "1.4",
            fontWeight: "600",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "1.6",
            fontWeight: "400",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "1",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
      },
    },
  },
  plugins: [],
};
